import type { Metadata } from "next"
import "@/app/_assets/styles/globals.scss"

// components
import NavBar from "@/app/_components/layouts/navbar"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function DefaultLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <>
            <NavBar></NavBar>
            <main className="container mx-auto">{children}</main>
        </>
    )
}
